git clone https://bitbucket.org/zunzuncode/zunzunsite3.git
git clone https://bitbucket.org/zunzuncode/pyeq3.git
git clone https://bitbucket.org/zunzuncode/tkinterstatsdistrofit.git
git clone https://bitbucket.org/zunzuncode/ramanspectroscopyfit.git
git clone https://bitbucket.org/zunzuncode/cherrypyfit.git
git clone https://bitbucket.org/zunzuncode/bottlefit.git
git clone https://bitbucket.org/zunzuncode/flaskfit.git
git clone https://bitbucket.org/zunzuncode/pyeq2.git
git clone https://bitbucket.org/zunzuncode/zunzunsite.git
git clone https://bitbucket.org/zunzuncode/commonproblems.git
git clone https://bitbucket.org/zunzuncode/tkinterfit.git
git clone https://bitbucket.org/zunzuncode/wxpythonfit.git
git clone https://bitbucket.org/zunzuncode/pyqt5fit.git
git clone https://bitbucket.org/zunzuncode/pygtkfit.git
